def MostrarMenudeIngreso():
    print("//////////////////////")
    print("// MENU DE INGRESO  //")
    print("//////////////////////")
    print("1. Iniciar como Camper. ")
    print("2. Iniciar como Trainer. ")
    print("3. Iniciar como Coordinador. ")
def MostrarMenudeCamper():
    print("//////////////////////")
    print("// MENU DE CAMPER   //")
    print("//////////////////////")
    print("1. Inscribirse")
    print("2. Ver cursos inscritos")
    print("3. Ver notas")
def MostrarMenudeTrainer():
    print("//////////////////////")
    print("// MENU DE TRAINER   //")
    print("//////////////////////")
    print("1. Cuales rutas dirijo?. ")
def MostrarMenudeCoordinador():
    print("//////////////////////")
    print("/MENU DE COORDINADOR /")
    print("//////////////////////")
    print("1. Asignar Notas")
    print("2. Asignar grupos")
    print("3. Abrir Menu CRUD (Create, Read, Update, Delete)")
def MostrarMenuCrudCoordinador ():
    print("\n//////////////////////")
    print("// CRUD COORDINADOR  //")
    print("//////////////////////")
    print("1. Agregar Camper/Trainer.")
    print("2. Agregar ruta de entrenamiento.")
    print("3. Suspender Camper/Trainer.")
    print("4. Ver lista de Campers/Trainers.")
    print("5. Modificar datos de Camper/Trainer.")