def MostrarMenudeIngreso():
    print("//////////////////////")
    print("// MENÚ DE INGRESO  //")
    print("//////////////////////")
    print("1. Iniciar como Camper")
    print("2. Iniciar como Trainer")
    print("3. Iniciar como Coordinador")
def MostrarMenudeCamper():
    print("//////////////////////")
    print("// MENÚ DE CAMPER   //")
    print("//////////////////////")
    print("1. Inscribirse")
def MostrarMenudeTrainer():
    print("//////////////////////")
    print("// MENÚ DE TRAINER   //")
    print("//////////////////////")
    print("1. Ver Campers/Trainers")
    print("2. Asignar notas")
def MostrarMenudeCoordinador():
    print("//////////////////////")
    print("/MENÚ DE COORDINADOR /")
    print("//////////////////////")
    print("1. Asignar notas")
    print("2. Asignar grupos")
    print("3. Abrir Menu CRUD (Create, Read, Update, Delete)")
    print("4. Módulo Reportes")
def MostrarMenuCrudCoordinador():
    print("\n//////////////////////")
    print("// CRUD COORDINADOR  //")
    print("//////////////////////")
    print("1. Ver Campers/Trainers")
    print("2. Agregar Camper/Trainer")
    print("3. Editar Camper/Trainer")
    print("4. Eliminar Camper/Trainer")
    print("5. Agregar ruta de entrenamiento")