def MostrarMenudeIngreso():
    print("//////////////////////")
    print("// MENÚ DE INGRESO  //")
    print("//////////////////////")
    print("1. Iniciar como Camper")
    print("2. Iniciar como Trainer")
    print("3. Iniciar como Coordinador")
def MostrarMenudeCamper():
    print("//////////////////////")
    print("// MENÚ DE CAMPER   //")
    print("//////////////////////")
    print("1. Inscribirse")
    print("2. Ver cursos inscritos")
    print("3. Ver notas")
def MostrarMenudeTrainer():
    print("//////////////////////")
    print("// MENÚ DE TRAINER   //")
    print("//////////////////////")
    print("1. Ver Campers/Trainers")
    print("2. Ver Grupos asignados")
    print("3. Asignar Notas")
def MostrarMenudeCoordinador():
    print("//////////////////////")
    print("/MENÚ DE COORDINADOR /")
    print("//////////////////////")
    print("1. Asignar Notas")
    print("2. Asignar grupos")
    print("3. Abrir Menu CRUD (Create, Read, Update, Delete)")
def MostrarMenuCrudCoordinador():
    print("\n//////////////////////")
    print("// CRUD COORDINADOR  //")
    print("//////////////////////")
    print("1. Ver Campers/Trainers")
    print("2. Agregar Camper/Trainer")
    print("3. Editar Camper/Trainer")
    print("4. Eliminar Camper/Trainer")
    print("5. Agregar ruta de entrenamiento")